#!/bin/bash
#
# beanstalkd
#
# chkconfig: - 85 15
# description: start, stop, restart beanstalkd
#              
# started by monit

RETVAL=0

start() {
/usr/local/bin/beanstalkd -d
ps aux | grep '[b]eanstalkd' | awk '{print $2}' > /pipeline/beanstalkd.pid
ps aux | grep '[b]eanstalkd' | grep -v /etc/ | awk '{print $2}' > /pipeline/beanstalkd.pid
}

stop() {
kill -9 `cat /pipeline/beanstalkd.pid`
rm /pipeline/beanstalkd.pid
}

case "$1" in
    start)
      start
      RETVAL=$?
  ;;
    stop)
      stop
      RETVAL=$?
  ;;
    restart)
      stop
      sleep 2
      start
      RETVAL=$?
  ;;
    *)
      echo "Usage: beanstalkd {start|stop|restart}"
      exit 1
  ;;
esac      

exit $RETVAL



