#!/bin/bash
#
# rake reporter
#
# chkconfig: - 85 15
# description: start, stop, restart reporter
#              
# started by monit

RETVAL=0

start() {
cd /pipeline/vipdac/ && /usr/bin/rake reporter:run RAILS_ENV=production & >> /dev/null
}

stop() {
kill -9 `cat /pipeline/reporter.pid`
rm /pipeline/reporter.pid
}

case "$1" in
    start)
      start
      RETVAL=$?
  ;;
    stop)
      stop
      RETVAL=$?
  ;;
    restart)
      stop
      sleep 2
      start
      RETVAL=$?
  ;;
    *)
      echo "Usage: reporter {start|stop|restart}"
      exit 1
  ;;
esac      

exit $RETVAL



