#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

rm -rf /etc/monit/reporter*
rm -rf /etc/init.d/reporter
cd /pipeline/vipdac/lib
/pipeline/vipdac/lib/build_monitrc.rb
rm -rf /pipeline/*.pid
rm -rf /pipeline/vipdac/log/*.pid
cd ..
sudo rake gems:install RAILS_ENV=production
sudo rake db:create:all RAILS_ENV=production
sudo rake db:migrate RAILS_ENV=production
chmod 666 /pipeline/vipdac/log/production.log
sleep 1
echo "Loading node..."
/usr/local/bin/monit

exit 0
